const test = require("node:test")
const assert = require("node:assert/strict")

const {
  addInterval,
  calculateNextRunAt,
  collectDueOccurrences,
  buildGeneratedExpenseData,
  hasGeneratedOccurrence,
  processRecurringExpense,
} = require("./recurring_expense.js")

class FakeRecord {
  constructor(collection) {
    this.collection = collection
    this.values = {}
    this.id = ""
  }

  set(key, value) {
    this.values[key] = value
    if (key === "id") this.id = value
  }

  getString(key) {
    return String(this.values[key] || "")
  }

  getInt(key) {
    return Number(this.values[key] || 0)
  }

  getFloat(key) {
    return Number(this.values[key] || 0)
  }

  getStringSlice(key) {
    const value = this.values[key]
    return Array.isArray(value) ? value.slice() : []
  }
}

global.Record = FakeRecord

function createRecurringRule(values) {
  return {
    id: values.id || "rule-1",
    values: { ...values },
    setCalls: [],
    getString(key) {
      return String(this.values[key] || "")
    },
    getInt(key) {
      return Number(this.values[key] || 0)
    },
    getFloat(key) {
      return Number(this.values[key] || 0)
    },
    getStringSlice(key) {
      const value = this.values[key]
      return Array.isArray(value) ? value.slice() : []
    },
    set(key, value) {
      this.values[key] = value
      this.setCalls.push([key, value])
    },
  }
}

test("addInterval advances by supported units from the scheduled time", () => {
  assert.equal(addInterval("2026-06-12 00:00:00.000Z", "day", 3), "2026-06-15 00:00:00.000Z")
  assert.equal(addInterval("2026-06-12 00:00:00.000Z", "week", 2), "2026-06-26 00:00:00.000Z")
  assert.equal(addInterval("2026-01-12 00:00:00.000Z", "month", 2), "2026-03-12 00:00:00.000Z")
  assert.equal(addInterval("2026-06-12 00:00:00.000Z", "year", 1), "2027-06-12 00:00:00.000Z")
})

test("addInterval clamps month-end and leap-year rollover safely", () => {
  assert.equal(addInterval("2025-01-31 00:00:00.000Z", "month", 1), "2025-02-28 00:00:00.000Z")
  assert.equal(addInterval("2024-02-29 00:00:00.000Z", "year", 1), "2025-02-28 00:00:00.000Z")
})

test("calculateNextRunAt uses the previous scheduled occurrence rather than now", () => {
  assert.equal(
    calculateNextRunAt({
      previousScheduledFor: "2026-02-01 00:00:00.000Z",
      now: "2026-09-15 00:00:00.000Z",
      intervalUnit: "month",
      intervalCount: 1,
    }),
    "2026-03-01 00:00:00.000Z"
  )
})

test("collectDueOccurrences catches up missed monthly runs in chronological order", () => {
  const runs = collectDueOccurrences({
    nextRunAt: "2026-01-01 00:00:00.000Z",
    now: "2026-04-15 00:00:00.000Z",
    intervalUnit: "month",
    intervalCount: 1,
    limit: 12,
  })

  assert.deepEqual(runs, [
    "2026-01-01 00:00:00.000Z",
    "2026-02-01 00:00:00.000Z",
    "2026-03-01 00:00:00.000Z",
    "2026-04-01 00:00:00.000Z",
  ])
})

test("collectDueOccurrences enforces the catch-up limit", () => {
  const runs = collectDueOccurrences({
    nextRunAt: "2026-01-01 00:00:00.000Z",
    now: "2026-01-10 00:00:00.000Z",
    intervalUnit: "day",
    intervalCount: 1,
    limit: 3,
  })

  assert.deepEqual(runs, [
    "2026-01-01 00:00:00.000Z",
    "2026-01-02 00:00:00.000Z",
    "2026-01-03 00:00:00.000Z",
  ])
})

test("collectDueOccurrences fails with a controlled error for invalid scheduler dates", () => {
  assert.throws(
    () =>
      collectDueOccurrences({
        nextRunAt: "not-a-date",
        now: "2026-01-10 00:00:00.000Z",
        intervalUnit: "day",
        intervalCount: 1,
        limit: 3,
      }),
    (error) => {
      assert.equal(error && error.code, "RECURRING_EXPENSE_INVALID_SCHEDULE")
      assert.match(error.message, /invalid nextRunAt/i)
      return true
    }
  )
})

test("buildGeneratedExpenseData attaches recurring metadata and preserves expense fields", () => {
  const record = buildGeneratedExpenseData({
    recurringId: "rule-1",
    scheduledFor: "2026-06-12 00:00:00.000Z",
    household: "home-1",
    description: "Rent",
    amount: 650,
    paidBy: "user-1",
    splitBetween: ["user-1", "user-2"],
    splitMode: "equal",
    splitShares: "",
    notes: "Autogenerated",
    createdBy: "user-1",
  })

  assert.deepEqual(record, {
    household: "home-1",
    description: "Rent",
    amount: 650,
    paidBy: "user-1",
    splitBetween: ["user-1", "user-2"],
    splitMode: "equal",
    splitShares: "",
    notes: "Autogenerated",
    recurringExpense: "rule-1",
    scheduledFor: "2026-06-12 00:00:00.000Z",
    createdBy: "user-1",
  })
})

test("hasGeneratedOccurrence queries expenses by recurringExpense and scheduledFor", () => {
  let call = null
  const app = {
    findRecordsByFilter(collection, filter, sort, limit, offset, params) {
      call = { collection, filter, sort, limit, offset, params }
      return [{}]
    },
  }

  const result = hasGeneratedOccurrence(app, "rule-1", "2026-06-12 00:00:00.000Z")

  assert.equal(result, true)
  assert.deepEqual(call, {
    collection: "expenses",
    filter: "recurringExpense = {:recurringExpense} && scheduledFor = {:scheduledFor}",
    sort: "",
    limit: 1,
    offset: 0,
    params: {
      recurringExpense: "rule-1",
      scheduledFor: "2026-06-12 00:00:00.000Z",
    },
  })
})

test("processRecurringExpense skips duplicates and saves only new due occurrences", () => {
  const saved = []
  const duplicateKeys = new Set(["rule-1::2026-01-01 00:00:00.000Z"])
  let nextExpenseId = 1
  const txApp = {
    findCollectionByNameOrId(name) {
      return { name }
    },
    findRecordsByFilter(collection, filter, sort, limit, offset, params) {
      const key = params.recurringExpense + "::" + params.scheduledFor
      return duplicateKeys.has(key) ? [{}] : []
    },
    save(record) {
      if (record.collection && record.collection.name === "expenses" && !record.id) {
        record.id = "expense-" + nextExpenseId
        nextExpenseId += 1
      }
      saved.push(record)
    },
  }

  const rule = createRecurringRule({
    id: "rule-1",
    nextRunAt: "2026-01-01 00:00:00.000Z",
    intervalUnit: "month",
    intervalCount: 1,
    household: "home-1",
    description: "Rent",
    amount: 650,
    paidBy: "user-1",
    splitBetween: ["user-1", "user-2"],
    splitMode: "equal",
    splitShares: "",
    notes: "",
    createdBy: "user-1",
  })

  const result = processRecurringExpense(txApp, rule, "2026-03-15 00:00:00.000Z")

  assert.deepEqual(result.generated, [
    "2026-02-01 00:00:00.000Z",
    "2026-03-01 00:00:00.000Z",
  ])
  assert.equal(result.skippedDuplicates, 1)
  assert.equal(saved.length, 3)
  assert.equal(saved[0].values.recurringExpense, "rule-1")
  assert.equal(saved[0].values.scheduledFor, "2026-02-01 00:00:00.000Z")
  assert.equal(saved[1].values.scheduledFor, "2026-03-01 00:00:00.000Z")
  assert.equal(saved[2], rule)
  assert.equal(rule.values.lastGeneratedExpense, "expense-2")
  assert.equal(rule.values.lastRunAt, "2026-03-01 00:00:00.000Z")
  assert.equal(rule.values.nextRunAt, "2026-04-01 00:00:00.000Z")
  assert.equal(rule.values.lastError, "")
})

test("processRecurringExpense clears stale errors when all due runs are duplicate matches", () => {
  const saved = []
  const duplicateKeys = new Set([
    "rule-1::2026-01-01 00:00:00.000Z",
    "rule-1::2026-02-01 00:00:00.000Z",
  ])
  const txApp = {
    findCollectionByNameOrId(name) {
      return { name }
    },
    findRecordsByFilter(collection, filter, sort, limit, offset, params) {
      const key = params.recurringExpense + "::" + params.scheduledFor
      return duplicateKeys.has(key) ? [{}] : []
    },
    save(record) {
      saved.push(record)
    },
  }

  const rule = createRecurringRule({
    id: "rule-1",
    nextRunAt: "2026-01-01 00:00:00.000Z",
    intervalUnit: "month",
    intervalCount: 1,
    household: "home-1",
    description: "Rent",
    amount: 650,
    paidBy: "user-1",
    splitBetween: ["user-1", "user-2"],
    splitMode: "equal",
    splitShares: "",
    notes: "",
    createdBy: "user-1",
    lastError: "previous failure",
  })

  const result = processRecurringExpense(txApp, rule, "2026-02-20 00:00:00.000Z")

  assert.deepEqual(result.generated, [])
  assert.equal(result.skippedDuplicates, 2)
  assert.equal(saved.length, 1)
  assert.equal(saved[0], rule)
  assert.equal(rule.values.lastError, "")
  assert.equal(rule.values.lastRunAt, "2026-02-01 00:00:00.000Z")
  assert.equal(rule.values.nextRunAt, "2026-03-01 00:00:00.000Z")
})
